package lab06;
import java.awt.*;
import simView.*;

public class UserMath extends ViewableDigraph 
{

	public UserMath()
	{
		super("user_math");
		
		ViewableAtomic u = new User("user", 10);
		ViewableDigraph m = new Math("math", 10);

		add(u);
		add(m);
		
		addCoupling(u, "out", m, "in");
		addCoupling(m, "out", u, "in");
	}
	
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(980, 644);
        ((ViewableComponent)withName("math")).setPreferredLocation(new Point(275, 205));
        ((ViewableComponent)withName("user")).setPreferredLocation(new Point(73, 51));
    }
 }
